### PR TITLE
Port Ranges

### PR DESCRIPTION
**Pull request by steinbrueckri**
Now it is possible to use Ranges for ports as well.

### CODE REVIEW

**Comment by kunzese** [comment]
@steinbrueckri Maybe we close this PR and open a new one to workaround the CLA sign issue.

**Comment by kristakhare** [comment]
Hi there! I'm trying to figure out if there's an objection to signing the CLA, or a technical issue in trying to do so. Please let me know if I can help. CC: @johnRiv

**Comment by kunzese** [comment]
@kristakhare it's a technical issue. I would like to sign the CLA and get this PR merged, but i receive a request timeout if i click on "I Agree" at https://cla-assistant.io/Comcast/snowdrift?pullRequest=2.

I opened a issues on the cla-assistant repo in may without success 😢 
https://github.com/cla-assistant/cla-assistant/issues/440

**Comment by JohnRiv** [comment]
I see kunzese signed out CLA on 3/18/19... not sure why the tool isn't recognizing it for this PR, but we should be good to merge this

**Comment by kunzese** [comment]
@JohnRiv if you can remove my old consent, i will be happy to sign it again.

**Comment by JohnRiv** [comment]
The tool seems to be slow today & I'd rather get it in... @dmuth I'm OK with you just merging this if you're happy with the code. If you're unable to override CLA Assistant's block on this PR let me know and I'll merge it.

**Comment by dmuth** [comment]
Sorry for the delay in getting on this, I've been thinking about how to go about building some testing so I can verify that the script continues to operate correctly.

I ended up writing https://github.com/Comcast/snowdrift/issues/3 to track development on building in some testing, with merging this PR as part of that Issue.

Do let me know if there are any questions, thanks!

-- Doug

**Comment by dmuth** [comment]
Update: I've begun working on that branch.  My work can be followed in #3.

-- Doug

**Comment by dmuth** [comment]
Hey @steinbrueckri, thanks for being so patient.  I just finished up my work in #3 and merged it to `master`. 

If you run `test.sh`, that should stand up a Dockerized testing environment and run some tests.  (Note: the test may fail on the first run due to the containers not having yet started yet, I have a note in `TODO` to address that.)

From here, I think may plan is to do the following:

- Create another branch, and pull your changes in
- Write tests for `snowdrift` based on your changes, and update `test.sh` accordingly.  (I will create additional Docker containers accordingly)

Once I've verified functionality, I'll merge to `master` and we should be good!

Let me know if you have any thoughts on that approach, otherwise I'll start on that this week.

Thanks,

-- Doug

**Comment by steinbrueckri** [comment]
Hi @dmuth,
thx for the update, that sounds like an plan. 👍🎉

**Comment by dmuth** [comment]
Good news!  I'm pretty much done at this point with my `testing-framework` branch and have merged it into `master`.  When I work on Snowdrift next (this weekend/next week), I'll pull in your changes, write some tests for port ranges, and we'll be good to merge into `master`!  

If you'd like to play around with the testing framework in the meantime, feel free to merge `master` into your branch.

-- Doug

**Comment by dmuth** [comment]
Okay, this has been merged.  Thank you for your contributions, and sorry for the lengthy delay on my part.  I will add the updated script to https://github.com/Comcast/homebrew-opensource shortly.

**Pull request merged**
