### PR TITLE
Added support for comma seperated port list

### PR DESCRIPTION
**Pull request by biehlera**
Added support for comma separated, tests missing come soon.

### CODE REVIEW

**Comment by steinbrueckri** [comment]
@biehlera Now that you have also adjusted the tests, you can also set the PR to "Ready for review".

**Comment by dmuth** [comment]
I'm unclear if this is in its final state, but I [figured out how to check out the PR on my end](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally) and saw what looks like a typo in one of the tests:

image

image

Also, don't forget to adjust the right-hand side of the calls to `compareValues` at the end of `test.sh`, as those are basically assertions.

Thanks for the efforts so far!

-- Doug

**Comment by steinbrueckri** [comment]
@dmuth Maybe I find some time the next weeks to implement the tests with GitHub for automated tests, I think that will make the review easier. 😅

Br Richard

**Comment by dmuth** [comment]
Things are looking better!  I see that all tests are working correctly here.  Just need to adjust the values checked in the assertions at the end and this PR should be complete:

image

I would also ask if you wouldn't mind doing an interactive rebase to squash all of the commits into a single commit, which makes my reviewing easier.  If you're not comfortable doing that, let me know and I can take care of it.

Also, just tossing this in here for my own benefit, here's how I checked out the PR: `git fetch origin pull/7/head:pr7 && git checkout pr7`.  Super useful!

Thanks,

-- Doug

**Comment by steinbrueckri** [comment]
@dmuth Rebase done, FYI!

**Comment by dmuth** [comment]
Almost there!  Just one assertion left to fix:

image

Let me know if you have any questions.

(That also got me thinking--after we get this merged, I'm going to revisit the testing script, so that I can avoid this particular sequence of events in future.)

-- Doug

**Comment by biehlera** [comment]
adjusted the value for failed tests

**Comment by dmuth** [comment]
Looks good to me!

image

I see that things got unsqaushed, but that's cool--I'm gonna try squashing the commits through GitHub during the merge.  Thank you for this contribution, it's super helpful!

**Comment by dmuth** [comment]
BTW @biehlera, I felt so bad about the back and forth towards the end, I went and overhauled the test system in PR #10.  That should ensure that what happened with this PR will never trouble anyone again. :-)

**Comment by biehlera** [comment]
> BTW @biehlera, I felt so bad about the back and forth towards the end, I went and overhauled the test system in PR #10. That should ensure that what happened with this PR will never trouble anyone again. :-)

No problem at all !! Thx for implementing my PR

**Pull request merged**
